USE [master]
GO

CREATE DATABASE [nancybook] ON  PRIMARY 
( NAME = N'nancybook', FILENAME = N'nancybook.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'nancybook_log', FILENAME = N'nancybook_log.ldf' , SIZE = 2816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [nancybook] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [nancybook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [nancybook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [nancybook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [nancybook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [nancybook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [nancybook] SET ARITHABORT OFF 
GO

ALTER DATABASE [nancybook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [nancybook] SET AUTO_CREATE_STATISTICS OFF 
GO

ALTER DATABASE [nancybook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [nancybook] SET AUTO_UPDATE_STATISTICS OFF 
GO

ALTER DATABASE [nancybook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [nancybook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [nancybook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [nancybook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [nancybook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [nancybook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [nancybook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [nancybook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [nancybook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [nancybook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [nancybook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [nancybook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [nancybook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [nancybook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [nancybook] SET  READ_WRITE 
GO

ALTER DATABASE [nancybook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [nancybook] SET  MULTI_USER 
GO

ALTER DATABASE [nancybook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [nancybook] SET DB_CHAINING OFF 
GO


